[build]
builder = "NIXPACKS"
buildCommand = "cd server && npm run build"

[deploy]
startCommand = "cd server && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_VERSION = "22.12.0"
PORT = "8787"
